// export default {
//   login: 'john-smilga',
//   id: 42133389,
//   node_id: 'MDQ6VXNlcjQyMTMzMzg5',
//   avatar_url: 'https://avatars3.githubusercontent.com/u/42133389?v=4',
//   gravatar_id: '',
//   url: 'https://api.github.com/users/justimnax',
//   html_url: 'https://github.com/john-smilga',
//   followers_url: 'https://api.github.com/users/john-smilga/followers',
//   following_url:
//     'https://api.github.com/users/john-smilga/following{/other_user}',
//   gists_url: 'https://api.github.com/users/john-smilga/gists{/gist_id}',
//   starred_url:
//     'https://api.github.com/users/john-smilga/starred{/owner}{/repo}',
//   subscriptions_url: 'https://api.github.com/users/john-smilga/subscriptions',
//   organizations_url: 'https://api.github.com/users/john-smilga/orgs',
//   repos_url: 'https://api.github.com/users/john-smilga/repos',
//   events_url: 'https://api.github.com/users/john-smilga/events{/privacy}',
//   received_events_url:
//     'https://api.github.com/users/john-smilga/received_events',
//   type: 'User',
//   site_admin: false,
//   name: 'John Smilga',
//   company: 'Coding Addict',
//   blog: 'www.johnsmilga.com',
//   location: 'Los Angeles',
//   email: null,
//   hireable: null,
//   bio: 'Creator of Coding Addict',
//   twitter_username: 'john_smilga',
//   public_repos: 152,
//   public_gists: 0,
//   followers: 1495,
//   following: 0,
//   created_at: '2018-08-06T06:48:23Z',
//   updated_at: '2020-07-08T05:01:32Z',
// };



export default {
  login: 'justimnax',
  id: 78740057,
  node_id: 'MDQ6VXNlcjc4NzQwMDU3',
  avatar_url: 'https://avatars.githubusercontent.com/u/78740057?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/justimnax',
  html_url: 'https://github.com/justimnax',
  followers_url: 'https://api.github.com/users/justimnax/followers',
  following_url:
    'https://api.github.com/users/justimnax/following{/other_user}',
  gists_url: 'https://api.github.com/users/justimnax/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/justimnax/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/justimnax/subscriptions',
  organizations_url: 'https://api.github.com/users/justimnax/orgs',
  repos_url: 'https://api.github.com/users/justimnax/repos',
  events_url: 'https://api.github.com/users/justimnax/events{/privacy}',
  received_events_url: 'https://api.github.com/users/justimnax/received_events',
  type: 'User',
  site_admin: false,
  name: 'jasem nazeri',
  company: 'coursee',
  blog: 'justimpro.ir',
  location: 'Ahvaz',
  email: 'justimnazu@gmail.com',
  hireable: null,
  bio: 'i am a very strong developer',
  twitter_username: 'justim',
  public_repos: 100,
  public_gists: 50,
  followers: 25069,
  following: 136,
  created_at: '2021-02-08T13:43:05Z',
  updated_at: '2022-07-03T16:42:52Z',
};